# Generated by Django 3.0.8 on 2020-07-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Pabellones',
            },
        ),
    ]
