# Generated by Django 3.0.8 on 2020-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0004_auto_20200713_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('generoMusical', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Artistas',
            },
        ),
    ]
