# Generated by Django 3.0.8 on 2020-07-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0005_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseñador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pasaporte', models.IntegerField()),
                ('paisOrigen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Diseñadores',
            },
        ),
    ]
