# Generated by Django 3.0.8 on 2020-07-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0006_diseñador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('coleccion', models.CharField(max_length=50)),
                ('Artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.Artista')),
                ('Diseñador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.Diseñador')),
            ],
            options={
                'verbose_name_plural': 'Desfiles',
            },
        ),
    ]
